=== kavispires/tardedivertida/src/utils/game-info.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "gameCode": {
      "type": "string"
    },
    "gameName": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "title": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": ["pt", "en"]
    },
    "popularName": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": ["pt", "en"]
    },
    "basedOn": {
      "type": "string"
    },
    "summary": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": ["pt", "en"]
    },
    "appearance": {
      "type": "object",
      "properties": {
        "color": {
          "type": "string"
        },
        "clouds": {
          "type": "string"
        },
        "backgroundColor": {
          "type": "string"
        }
      },
      "required": ["color", "clouds"]
    },
    "rules": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "en": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["pt", "en"]
    },
    "playerCount": {
      "type": "object",
      "properties": {
        "best": {
          "type": "integer"
        },
        "recommended": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "min": {
          "type": "integer"
        },
        "max": {
          "type": "integer"
        }
      },
      "required": ["recommended", "min", "max"]
    },
    "duration": {
      "type": "object",
      "properties": {
        "base": {
          "type": "number"
        },
        "perPlayer": {
          "type": "number"
        }
      },
      "required": ["base", "perPlayer"]
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "competitive",
          "cooperative",
          "same-time",
          "turn-based",
          "drawing",
          "writing",
          "guessing",
          "voting",
          "pairing",
          "push-your-luck",
          "brain-burner",
          "discussion",
          "timed",
          "traitor",
          "images",
          "betting",
          "achievements",
          "bots",
          "mobile-friendly",
          "audience-mode"
        ]
      }
    },
    "available": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "boolean"
        },
        "en": {
          "type": "boolean"
        }
      },
      "required": ["pt", "en"]
    },
    "options": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "key": {
            "type": "string"
          },
          "off": {
            "type": "string"
          },
          "on": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "disabled": {
            "type": "boolean"
          }
        },
        "required": ["label", "key", "off", "on"]
      }
    }
  },
  "required": [
    "gameCode",
    "gameName",
    "version",
    "title",
    "popularName",
    "basedOn",
    "summary",
    "rules",
    "playerCount",
    "tags",
    "available",
    "appearance"
  ]
}

=== kavispires/tardedivertida/src/games/caminhos-magicos/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "Z",
  "gameName": "caminhos-magicos",
  "version": "none",
  "title": {
    "pt": "Caminhos Mágicos",
    "en": "Magic Pathways"
  },
  "popularName": {
    "pt": "Do labirinto de palavras",
    "en": ""
  },
  "basedOn": "shtaP citsyM",
  "appearance": {
    "clouds": "cloud",
    "color": ""
  },
  "summary": {
    "pt": "Jogadores tem que descobrir qual caminho devem seguir num labirinto de palavras usando adjetivos e lógica",
    "en": "Players must find the right path in a word maze using adjectives and logic"
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "best": 4,
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 8
  },
  "tags": ["competitive", "guessing", "same-time", "pairing"],
  "available": {
    "pt": false,
    "en": false
  }
}

=== kavispires/tardedivertida/src/games/fileira-de-fatos/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "Î¹",
  "gameName": "fileira-de-fatos",
  "version": "planned",
  "title": {
    "pt": "Fileira De Fatos",
    "en": "Facts Lineup"
  },
  "popularName": {
    "pt": "",
    "en": ""
  },
  "basedOn": "Template",
  "summary": {
    "pt": "Jogadores respondem uma pergunta com um numero secretamente e tem que colocar todas as respostas em ordem",
    "en": "TBD"
  },
  "appearance": {
    "clouds": "cloud",
    "color": "",
    "backgroundColor": ""
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10
  },
  "tags": ["competitive", "same-time", "writing", "guessing"],
  "available": {
    "pt": false,
    "en": false
  }
}

=== kavispires/tardedivertida/src/games/labirinto-secreto/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "Z",
  "gameName": "labirinto-secreto",
  "version": "beta",
  "title": {
    "pt": "Labirinto Secreto",
    "en": "Secret Labyrinth"
  },
  "popularName": {
    "pt": "Das árvores",
    "en": "The trees game"
  },
  "basedOn": "shtaP citsyM",
  "appearance": {
    "clouds": "cloud",
    "color": ""
  },
  "summary": {
    "pt": "Jogadores tem que descobrir qual caminho devem seguir num labirinto de palavras usando adjetivos e lógica",
    "en": "Players must find the right path in a word maze using adjectives and logic"
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "best": 4,
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10
  },
  "duration": {
    "base": 0,
    "perPlayer": 0
  },
  "tags": ["competitive", "guessing", "same-time", "pairing"],
  "available": {
    "pt": true,
    "en": true
  }
}

=== kavispires/tardedivertida/src/games/arte-ruim/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "A",
  "gameName": "arte-ruim",
  "version": "5.0.18",
  "title": {
    "pt": "Arte Ruim Pra Dedéu",
    "en": "Questionable Art"
  },
  "popularName": {
    "pt": "ARPD",
    "en": "The one you draw in 10 seconds"
  },
  "basedOn": "trA daB yllaeR",
  "summary": {
    "pt": "Tente identificar as obras-primas criadas por seus oponentes!",
    "en": "Try to guess the masterpieces created by your opponents"
  },
  "appearance": {
    "clouds": "artsy-clouds",
    "color": "#8c4103",
    "backgroundColor": "rgba(255, 255, 255, 0.95)"
  },
  "rules": {
    "pt": [
      "Arte Ruim Pra Dedéu é um jogo competitivo que os jogadores tentam adivinhar o maior número de desenhos possíveis",
      "Em cada rodada, jogadores recebem uma carta com uma expressão e tem 10 segundos para desenhá-la.",
      "Após todos jogadores terminarem suas obras de arte, embaralha-se as cartas e os desenhos e todos tem que identificar qual desenho corresponde a cada expressão.",
      "Respostas corretas ganham 2 pontos e cada voto que seu desenho recebe também te dá 1 ponto.",
      "Quanto mais próximo do final do jogo, mais difíceis as expressões ficam! Fique esperto!",
      "Após 5 rodadas, o jogador com mais pontos é o vencedor!"
    ],
    "en": [
      "Questionable Art is a competitive game where players try to match artworks to their titles",
      "Every round, players get a card with an expression and have 10 seconds to draw it.",
      "After every player has completed their masterpiece, all expressions and artworks are shuffled and everybody has to match the correct piece to its title.",
      "Correct matches grants 2 points and every correct guess your drawing gets also gives you 1 point.",
      "As you advance the game, harder expressions will come up! Try to keep up!",
      "After 5 rounds, the game is over and the player with the most points wins!"
    ]
  },
  "playerCount": {
    "best": 6,
    "recommended": [4, 5, 6, 7, 8],
    "min": 3,
    "max": 10
  },
  "duration": {
    "base": 5,
    "perPlayer": 3
  },
  "tags": [
    "competitive",
    "same-time",
    "drawing",
    "pairing",
    "timed",
    "mobile-friendly",
    "achievements",
    "audience-mode"
  ],
  "available": {
    "pt": true,
    "en": true
  },
  "options": [
    {
      "label": "Cards",
      "key": "useAllCards",
      "off": "New cards",
      "on": "All cards",
      "description": "Use only cards that haven't been used before in any game"
    },
    {
      "label": "Duration",
      "key": "forPoints",
      "off": "5 Rounds",
      "on": "For Points",
      "description": "Point threshold is determined by the number of players (30-100)"
    },
    {
      "label": "Difficulty",
      "key": "randomize",
      "off": "Incremental",
      "on": "Randomized",
      "description": "Rounds will have random difficulty"
    },
    {
      "label": "Levels",
      "key": "specialLevels",
      "off": "Normal",
      "on": "Add Specials",
      "description": "One or more special levels will be added"
    }
  ]
}

=== kavispires/tardedivertida/src/games/duetos/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "D",
  "gameName": "duetos",
  "version": "planned",
  "title": {
    "pt": "Duetos",
    "en": "Duets"
  },
  "popularName": {
    "pt": "Dos pares",
    "en": "To pair things"
  },
  "basedOn": "souD",
  "summary": {
    "pt": "Fa√ßa pares com as cartas como os outros jogadores",
    "en": "Pair the cards like the other players"
  },
  "appearance": {
    "clouds": "cloud",
    "color": "",
    "backgroundColor": ""
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10
  },
  "tags": ["competitive", "pairing"],
  "available": {
    "pt": false,
    "en": false
  }
}

=== kavispires/tardedivertida/src/games/nao-sou-robo/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "B",
  "gameName": "nao-sou-robo",
  "version": "planned",
  "title": {
    "pt": "Eu Não Sou Um Robô",
    "en": "I'm Not A Robot"
  },
  "popularName": {
    "pt": "Cartas bonitos contro o robô",
    "en": "Image cards against the bot"
  },
  "basedOn": "stuanorienO",
  "summary": {
    "pt": "Descobra o robô entre as imagens",
    "en": "Find the bot among the images"
  },
  "appearance": {
    "clouds": "cloud",
    "color": "",
    "backgroundColor": ""
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10
  },
  "tags": ["cooperative", "images", "guessing", "same-time"],
  "available": {
    "pt": false,
    "en": false
  }
}

=== kavispires/tardedivertida/src/games/quem-sou-eu/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "Q",
  "gameName": "quem-sou-eu",
  "version": "cancelled",
  "title": {
    "pt": "Quem Sou Eu?",
    "en": "Who Am I?"
  },
  "popularName": {
    "pt": "",
    "en": ""
  },
  "basedOn": "znabdeH/ytirbeleC",
  "appearance": {
    "clouds": "cloud",
    "color": ""
  },
  "summary": {
    "pt": "Cada jogador é uma celebridade, você consegue adivinhar quem você é com 20 perguntas?",
    "en": "Can you guess who you are with 20 questions?"
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [3, 4, 5, 6],
    "min": 1,
    "max": 10
  },
  "duration": {
    "base": 0,
    "perPlayer": 0
  },
  "tags": ["cooperative", "discussion", "guessing"],
  "available": {
    "pt": false,
    "en": false
  }
}

=== kavispires/tardedivertida/src/games/dilema-dos-esquiadores/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "EE",
  "gameName": "dilema-dos-esquiadores",
  "version": "none",
  "title": {
    "pt": "Dilema dos Esquiadores",
    "en": "Skiers' Dilemma"
  },
  "popularName": {
    "pt": "",
    "en": ""
  },
  "basedOn": "ammeliD thgiR tfeL",
  "summary": {
    "pt": "Jogadores apostam em o que os outros vão decidir em uma série de escolhas",
    "en": "Players bet on what others are going to decide between a series of choices"
  },
  "appearance": {
    "clouds": "cloud",
    "color": "",
    "backgroundColor": ""
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10
  },
  "duration": {
    "base": 0,
    "perPlayer": 0
  },
  "tags": ["competitive", "same-time", "betting", "voting"],
  "available": {
    "pt": false,
    "en": false
  }
}
