=== kavispires/tardedivertida/src/utils/game-info.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "gameCode": {
      "type": "string"
    },
    "gameName": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "title": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": ["pt", "en"]
    },
    "popularName": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": ["pt", "en"]
    },
    "basedOn": {
      "type": "string"
    },
    "summary": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": ["pt", "en"]
    },
    "appearance": {
      "type": "object",
      "properties": {
        "color": {
          "type": "string"
        },
        "clouds": {
          "type": "string"
        },
        "backgroundColor": {
          "type": "string"
        }
      },
      "required": ["color", "clouds"]
    },
    "rules": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "en": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["pt", "en"]
    },
    "playerCount": {
      "type": "object",
      "properties": {
        "best": {
          "type": "integer"
        },
        "recommended": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "min": {
          "type": "integer"
        },
        "max": {
          "type": "integer"
        }
      },
      "required": ["recommended", "min", "max"]
    },
    "duration": {
      "type": "object",
      "properties": {
        "base": {
          "type": "number"
        },
        "perPlayer": {
          "type": "number"
        }
      },
      "required": ["base", "perPlayer"]
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "competitive",
          "cooperative",
          "same-time",
          "turn-based",
          "drawing",
          "writing",
          "guessing",
          "voting",
          "pairing",
          "push-your-luck",
          "brain-burner",
          "discussion",
          "timed",
          "traitor",
          "images",
          "betting",
          "achievements",
          "bots",
          "mobile-friendly",
          "audience-mode"
        ]
      }
    },
    "available": {
      "type": "object",
      "properties": {
        "pt": {
          "type": "boolean"
        },
        "en": {
          "type": "boolean"
        }
      },
      "required": ["pt", "en"]
    },
    "options": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "key": {
            "type": "string"
          },
          "off": {
            "type": "string"
          },
          "on": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "disabled": {
            "type": "boolean"
          }
        },
        "required": ["label", "key", "off", "on"]
      }
    }
  },
  "required": [
    "gameCode",
    "gameName",
    "version",
    "title",
    "popularName",
    "basedOn",
    "summary",
    "rules",
    "playerCount",
    "tags",
    "available",
    "appearance"
  ]
}

=== kavispires/tardedivertida/src/games/adedanhx/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "K",
  "gameName": "adedanhx",
  "version": "0.1.0",
  "title": {
    "pt": "Adedanhx",
    "en": "Stop-ish!"
  },
  "popularName": {
    "pt": "Adedanha de tabela",
    "en": "Stop with a twist"
  },
  "basedOn": "sgaT",
  "summary": {
    "pt": "Seja o primeiro a preencher a tabela com palavras que comecem com as letras sorteadas!",
    "en": "Be the first to fill the table with words that start with the drawn letters!"
  },
  "appearance": {
    "clouds": "letter-clouds",
    "color": "#3653ad",
    "backgroundColor": ""
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10
  },
  "tags": ["same-time", "timed", "writing", "competitive", "achievements"],
  "available": {
    "pt": true,
    "en": true
  }
}

=== kavispires/tardedivertida/src/games/retrato-falado/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "R",
  "gameName": "retrato-falado",
  "version": "1.8.8",
  "title": {
    "pt": "Retrato Falado Monstruoso",
    "en": "Monster Sketch"
  },
  "popularName": {
    "pt": "Do monstro",
    "en": ""
  },
  "basedOn": "ytiswardsnoM",
  "summary": {
    "pt": "Um monstro atacou a pobre testemunha. Ser√° que ela vai conseguir descrever o criminoso",
    "en": "A monster has attacked a poor witness. Will she be able to describe the perpetrator"
  },
  "appearance": {
    "clouds": "monster-eye-cloud",
    "color": "#9ea63b",
    "backgroundColor": "rgba(8, 60, 3, 0.5)"
  },
  "rules": {
    "pt": ["TBD"],
    "en": [
      "Every round a player will be the witness, they have seen a monster around doing monstrous criminal activities",
      "They have 20 seconds to memorize the monster's features. Immediately after they have 2 minutes to describe the monster to the other players",
      "Then each player including the witness vote for the sketch the best matches the original monster, that artist will get 1 point.",
      "If the witness voted with the group, it is a credible witness and it also gets a point, otherwise whoever the witness voted for gets 1 point"
    ]
  },
  "playerCount": {
    "recommended": [5, 6],
    "min": 4,
    "max": 10
  },
  "duration": {
    "base": 4,
    "perPlayer": 5
  },
  "tags": ["competitive", "drawing", "voting", "discussion", "timed"],
  "available": {
    "pt": true,
    "en": true
  }
}

=== kavispires/tardedivertida/src/games/sonhos-pesadelos/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "S",
  "gameName": "sonhos-pesadelos",
  "version": "0.9.1",
  "title": {
    "pt": "Sonhos e Pesadelos",
    "en": "Dreams and Nightmares"
  },
  "popularName": {
    "pt": "Das cartas bonitas e sonhos",
    "en": ""
  },
  "basedOn": "esuM",
  "summary": {
    "pt": "Às vezes, sonhos são bem difíceis de contar porque você só consegue lembrar fragmentos e colocar todas ideias juntas pode ser um desafio",
    "en": "Sometimes dreams are very hard to tell because you can only remember so many things among the fragments of your memory and trying to put your ideas together can be a challenge"
  },
  "appearance": {
    "clouds": "sky-clouds",
    "color": ""
  },
  "rules": {
    "pt": [
      "Em Sonhos e Pesadelos, os jogadores são paranormais num concurso de adivinhar os sonhos dos outros! Quando um jogador consegue adivinhar todos os sonhos corretamente numa mesma rodada, ele vence!",
      "Cada jogador será designado a um ou mais cartas que representam sonhos.Em cada uma das 6 rodadas, o jogo escolherá um tema aleatório e você deve escrever uma dica para cada um dos seus sonhos, sempre dentro do tema.",
      "Mas cuidado, você também terá cartas pesadelos que te impedem de ganhar se qualquer outro jogador achar que ele é o seu sonho. Então, escreva algo que claramente não pode ser nenhum dos seus pesadelos.",
      "Quando todos jogadores tiverem escrito seus sonhos, é hora de votar. Você tem que fazer combinações corretas entre dicas e sonhos.",
      "Se algum jogador escolher todos os pares corretamente e nenhum outro jogador tiver achado que sua dica é um de seus pesadelos. Ele ganha o jogo! Caso contrário, o jogo te avisa apesar quantos acertos você cometeu e próxima rodada.",
      "Após 4 rodadas, se ninguém tiver ganhado, temos uma última chance de apenas tentar adivinhar o maior número de sonhos."
    ],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10
  },
  "tags": ["competitive", "images", "writing", "pairing", "brain-burner"],
  "available": {
    "pt": true,
    "en": true
  }
}

=== kavispires/tardedivertida/src/games/teste-de-elenco/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "T",
  "gameName": "teste-de-elenco",
  "version": "alpha",
  "title": {
    "pt": "Teste De Elenco",
    "en": "Re-Casting Call"
  },
  "popularName": {
    "pt": "Preconceito grupal",
    "en": ""
  },
  "basedOn": "enoN",
  "summary": {
    "pt": "TBD",
    "en": "TBD"
  },
  "appearance": {
    "clouds": "cloud",
    "color": "",
    "backgroundColor": ""
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [4, 5, 6],
    "min": 2,
    "max": 10
  },
  "tags": ["competitive", "voting"],
  "available": {
    "pt": true,
    "en": true
  },
  "options": [
    {
      "key": "nsfw",
      "label": "NSFW questions",
      "off": "No",
      "on": "Yes",
      "description": "Allow NSFW questions"
    },
    {
      "label": "Original Cartoon",
      "key": "official",
      "off": "Cartoon",
      "on": "Official",
      "description": "Not recommended"
    },
    {
      "label": "Realistic",
      "key": "realistic",
      "off": "No",
      "on": "Yes",
      "description": "This setting has priority over any other above"
    },
    {
      "label": "Models",
      "key": "models",
      "off": "No",
      "on": "Yes",
      "description": "This setting has priority over any other above"
    },
    {
      "label": "Wacky",
      "key": "wacky",
      "off": "No",
      "on": "Yes",
      "description": "This setting has priority over any other above"
    }
  ]
}

=== kavispires/tardedivertida/src/games/cruza-palavras/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "X",
  "gameName": "cruza-palavras",
  "version": "4.0.7",
  "title": {
    "pt": "Cruza Palavras",
    "en": "Mixed Clues"
  },
  "popularName": {
    "pt": "Conectar duas palavras da grade",
    "en": ""
  },
  "basedOn": "seulC ssorC",
  "summary": {
    "pt": "Uma grade de palavras e várias coordenadas... você consegue associar todas as palavras?",
    "en": "A word grid and many coordinates... are you able to match all words?"
  },
  "appearance": {
    "clouds": "letter-clouds",
    "color": "#227168"
  },
  "rules": {
    "pt": ["TBD"],
    "en": [
      "You will get a coordinate in a grid of with words in their header columns and header rows. You must write a single word clue that connects both coordinates headers",
      "After everybody is done, everybody has to match the clues with the coordinates",
      "Getting the exact clue coordinate gets you 2 points, but if you get a right coordinate with a wrong clue, you still get 1 point",
      "Watch out, if nobody gets your clue, you lose points equal to the number of players, ouch",
      "A new bigger board will show up when there are not enough clues for each player and... will use the clues written by the players as coordinates",
      "The game ends after 6 rounds"
    ]
  },
  "playerCount": {
    "best": 4,
    "recommended": [4, 5, 6],
    "min": 3,
    "max": 10
  },
  "duration": {
    "base": 0,
    "perPlayer": 0
  },
  "tags": ["competitive", "same-time", "writing", "pairing", "brain-burner", "audience-mode"],
  "available": {
    "pt": true,
    "en": true
  },
  "options": [
    { "label": "Grid Size", "key": "largerGrid", "off": "Normal", "on": "Larger" },
    { "label": "Grid Type", "key": "imageGrid", "off": "Words", "on": "Images" }
  ]
}

=== kavispires/tardedivertida/src/games/comunicacao-alienigena/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "C",
  "gameName": "comunicacao-alienigena",
  "version": "2.1.18",
  "title": {
    "pt": "Comunicação Alienígena",
    "en": "Alien Language"
  },
  "popularName": {
    "pt": "de falar com ets",
    "en": ""
  },
  "basedOn": "tcatnoC tsriF",

  "summary": {
    "pt": "Será que um alienígena consegue se comunicar com os humanos?",
    "en": "Would the aliens be able to communicate with the humans?"
  },
  "appearance": {
    "clouds": "ufo-cloud",
    "color": "#6CC417",
    "backgroundColor": "rgba(53, 32, 48, 0.75)"
  },
  "rules": {
    "pt": ["TBD"],
    "en": ["TBD"]
  },
  "playerCount": {
    "recommended": [2, 3, 4],
    "min": 1,
    "max": 6,
    "best": 3
  },
  "duration": {
    "base": 20,
    "perPlayer": 3
  },
  "tags": ["cooperative", "turn-based", "drawing", "guessing", "brain-burner", "bots"],
  "available": {
    "pt": true,
    "en": true
  },
  "options": [
    {
      "key": "botAlien",
      "label": "Alien Bot",
      "off": "No",
      "on": "Yes",
      "description": "The bot will play as the alien and try to convey and guess clues through AI"
    }
  ]
}

=== kavispires/tardedivertida/src/games/megamix/game-info.json
{
  "$schema": "../../utils/game-info.schema.json",
  "gameCode": "Z",
  "gameName": "megamix",
  "version": "3.0.0",
  "title": {
    "pt": "Megamix",
    "en": "Megamix"
  },
  "popularName": {
    "pt": "Jogo da área vip",
    "en": "The VIP area game"
  },
  "basedOn": "sniW maeT neerG ehT",
  "summary": {
    "pt": "Responda uma pergunta e entre para área VIP!",
    "en": "Answer a question correctly and join the VIP area!"
  },
  "appearance": {
    "clouds": "vinyl-cloud",
    "color": "",
    "backgroundColor": ""
  },
  "rules": {
    "pt": [
      "Cada rodada um desafio baseado em um dos jogos do Tarde Divertida é lançado e se você estiver com a maioria você vai para o Time Vencedor. Após 15 rodadas, ganha o vencedor do Time Vencedor"
    ],
    "en": [
      "Each round there's a task based on the other games in the platform. If you match the majority of players, you are in the Winning Team. After 15 round, the winner in the Winning Team wins"
    ]
  },
  "playerCount": {
    "recommended": [5, 7, 9],
    "best": 7,
    "min": 4,
    "max": 16
  },
  "tags": ["competitive", "images", "drawing", "guessing", "pairing", "same-time", "writing", "voting"],
  "available": {
    "pt": true,
    "en": true
  },
  "options": [
    {
      "key": "nsfw",
      "label": "NSFW",
      "on": "Any content",
      "off": "Safe content",
      "description": "Some games might have inappropriate stuff",
      "disabled": true
    },
    {
      "key": "moreTracks",
      "label": "Game Based Tracks",
      "on": "More",
      "off": "Normal",
      "description": "3-5 special tracks vs 5-7 special tracks (Select Track types below)",
      "disabled": true
    },
    {
      "key": "imagesTrack",
      "label": "Images Track (recommended)",
      "on": "No",
      "off": "Yes",
      "description": "Adds one track based on Detective Agency, Dream Gallery, Obscure Doors or Story Tellers",
      "disabled": true
    },
    {
      "key": "charactersTrack",
      "label": "Characters Track (recommended)",
      "on": "No",
      "off": "Yes",
      "description": "Adds one track based Who Am I or Ultimate Champion",
      "disabled": true
    },
    {
      "key": "opinionsTrack",
      "label": "Opinions Track (recommended)",
      "on": "No",
      "off": "Yes",
      "description": "Adds one track based on That's Polemic, Facts Lineup, or The Skier's Dilemma",
      "disabled": true
    },
    {
      "key": "drawingTrack",
      "label": "Drawing Track",
      "on": "No",
      "off": "Yes",
      "description": "Adds one track based on Questionable Art or Monster Sketch",
      "disabled": true
    },
    {
      "key": "wordsTrack",
      "label": "Words Track",
      "on": "No",
      "off": "Yes",
      "description": "Adds one track based on That's It, Mixed Clues, or Herd Mind",
      "disabled": true
    },

    {
      "key": "judgingTrack",
      "label": "Judging Track",
      "on": "No",
      "off": "Yes",
      "description": "Adds one track based Eye Witness or Guess Who What. (NSFW)",
      "disabled": true
    },
    {
      "key": "specialTrack",
      "label": "Special Track",
      "on": "No",
      "off": "Yes",
      "description": "Adds one track based Alien Communication, or Telepathic Waves",
      "disabled": true
    },
    {
      "key": "unpopularTrack",
      "label": "Unpopular Track",
      "on": "No",
      "off": "Yes",
      "description": "Adds one track based Horrific Crimes, Movie Night, or Fear Street",
      "disabled": true
    }
  ]
}
